### ISSUE TITLE
Colisão de janelas com o painel superior

### ISSUE THREAD

**Issue by HidekiHrk** [meawto/meawto.github.io#2]
Seria interessante se o painel superior tivesse uma colisão com as janelas ao invés delas apenas atravessarem, isso evitaria a situação na qual os controls da janela ficam abaixo do painel.
Motivação: A maior parte das desktop environments contam com este recurso.
Seria interessante se inspirar um pouco no gnome para esse projeto xD
Tá ficando lindo demais, força pra ti mill

**Comment by meawto** [comment]
Inicialmente existia essa colisão, limitando a janela do jeito que você falou. Mas mudei a estrutura, jogando a taskbar dentro da div que limita as janelas, fazendo assim não existir a colisão na mesma. O motivo: para que o efeito blur fosse aplicado na mesma sobre o papel de parede

agradeço pela recomendação, irei aplicar isso futuramente (que inclusive é simples)

--
Sobre a inspiração no gnome: você se refere às funções ou a aparência do mesmo?

agradeço, para você também. Se cuida.

**Comment by HidekiHrk** [comment]
Me refiro às funções mesmo.

**Comment by meawto** [comment]
está bem, agradeço pela questão

**Comment by meawto** [comment]
resolvido. Agradeço pela colaboração, sua ajuda é muito bem-vinda para este projeto

commit: 626cb71815c0270cd1805dcf770799b172d2604a
